### ISSUE TITLE
Expected degree graph functions introduces bias in edge placement

### ISSUE THREAD

**Issue by ghyatzo** [JuliaGraphs/Graphs.jl#107]
**Description of bug**
Assume we are trying to build an Erdos-Renyi graph with order parameter `c=0.5`. We know that Erdos-Renyi random graphs develop a giant component at `c=1` and that they have Binomial degree distribution with parameters `n, p=c/n` or poisson with parameter `c` for large `n`.

let us sample a binomial degree distribution for `n=1000` nodes and `p = 0.5*inv(n)` and generate a graph with it

    julia> g = expected_degree_graph(rand(Binomial(n,p), n))
    {1000, 221} undirected simple Int64 graph

then generate an erdos-renyi graph with the built in constructor `er = erdos_renyi(n, p)`.

     julia> er = erdos_renyi(n, p)
    {1000, 257} undirected simple Int64 graph

they both generate a graph with the correct amount of edges `ne = p * binomial(n, 2)` of around `250` edges. 
Compare now the connected components of these graphs 

    julia> sort(map(length, connected_components(g)))
    780-element Vector{Int64}:
      1
       ...
      9
      14
      144

while a correct outcome should look like

    julia> sort(map(length, connected_components(er)))
    743-element Vector{Int64}:
      1
       ...
      10
      12
      13

These are just specific numbers, but the behaviour persists through multiple runs.

**How to reproduce**
See Above

**Expected behavior**
See Above

**Actual behavior**
See Above

**Code demonstrating bug**
```
c = 0.5
n = 1000
p = c/n

bin = Binomial(n,p)
d = rand(bin, n)
@assert isgraphical(d) # sample until we get a graphical sequence

g = expected_degree_graph(d)
er = erdos_renyi(n, p)

g_cc_dist = sort(map(length, connected_components(g)))
er_cc_dist = sort(map(length, connected_components(er)))
```

**Version information**
```
julia> versioninfo()
Julia Version 1.7.0
Commit 3bf9d17731 (2021-11-30 12:12 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.1.0)
  CPU: Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
Environment:
  JULIA_NUM_THREADS = 8
```

```
(project) pkg> status Graphs
     Project project v0.1.0
      Status `~/path/to/project/Project.toml`
  [86223c79] Graphs v1.6.0
```

**Additional context**

**Comment by etiennedeg** [comment]
`expected_degree_graph` does not guarantee a graph to be generated with the same probability density as `erdos-renyi`.
If we look at the doc of the function: "Given a vector of expected degrees ω indexed by vertex, create a random undirected graph in which vertices i and j are connected with probability ω[i]*ω[j]/sum(ω)".
If you enter as a degree sequence the list `[np, np, np, ...]`, the given graph should have the same distribution as `erdos-renyi`, because each edge will be chosen with a probability of `np*np/(n*np) = p`, which is exactly the definition of an erdos-renyi graph. If you enter the degree sequence with degrees following a binomial distribution, you are already biasing the graph to not follow an erdos_renyi distribution and to have a much bigger connected component.
Try plotting the graph `g = expected_degree_graph(fill(n*p, n))`, and you will see the same behavior as for a graph generated by `erdos-renyi`.

**Comment by ghyatzo** [comment]
mistakenly interpreted it would work with degree sequences sampled for a distribution, and not only from the expected value of the distribution you sample from.
