### ISSUE TITLE
Bug in randbn(n,p)

### ISSUE THREAD

**Issue by aurorarossi** [JuliaGraphs/Graphs.jl#193]
The function `randbn(n,p)` that returns a binomially-distributed random number with parameters $n$ and $p$. For every $n$, if $p=1$ it should return $n$ instead it loops.

**Comment by aurorarossi** [comment]
Binomial.jl test is not working  (but it is not included in runtests.jl). I suggest to change that tests.

**Comment by simonschoelly** [comment]
The random graphs in general is something we have to refactor at one point - form some graphs, I think we also kind of have an incorrect distribution.

In this PR I have added to the comments some code that I wrote a long time ago but never commited, that should take of the issue here. Maybe someone with a bit more time can take that old code and create a new PR out of it?

https://github.com/JuliaGraphs/Graphs.jl/pull/150
