### ISSUE TITLE
why is `weights` function in Graphs.jl and not in SimpleWeightedGraphs.jl?

### ISSUE THREAD

**Issue by hdavid16** [JuliaGraphs/Graphs.jl#216]
If there is a package for dealing with weighted graphs, wouldn't it make more sense to have the `weights` function there?

**Comment by simonschoelly** [comment]
I think it is here, so that the algorithms in this package can deal with any kind of weighted graphs. Then if someone implements a custom graph that has weighted edges, they can just implement the `weights` function for the graph type. Otherwise, we would need to also move all algorithms that take edge weights into consideration into the `SimpleWeightedGraphs` package.

**Comment by hdavid16** [comment]
Makes sense. Thanks!
