### ISSUE TITLE
Things to do before v1.9

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphs/Graphs.jl#306]
I looked a bit at the PRs that we have introduced since v1.8 - it looks mostly good, but there are a few things that we probably should fix before a next release, so that we don't introduce new bugs:

* [x] Remove the `GenericGraph(elist::Vector{Graphs.SimpleGraphEdge{T}})` function introduced in #232  => addressed in #308
* [x] Try to fix the bugs that we have on nightly - but I suspect that this might be an issue with JET.jl, so maybe we cannot.

**Minor**:
* [ ] #84 was merged, but that PR uses some magic constant - I am not completely sure that this is the right way - but on the other hand we could argue that this replaces a bug with another one, so maybe we can ignore it.

**Comment by gdalle** [comment]
Thanks for taking the time!

1. Wanna do it, since you wrote all of the `GenericGraph` infrastructure?
2. Yeah it has something to do with JET on nightly. My fix would be to keep nightly CI #295 but decoupling it from the "build passing" badge
3. Do you mean `dnz = abs.(diag(D)) .>= 1E-16`? Maybe we can do `eps(T)` instead?

**Comment by gdalle** [comment]
What do you think about https://github.com/JuliaGraphs/Graphs.jl/issues/307?

**Comment by gdalle** [comment]
Okay, it seems #307 can wait and so can the workaround from #84.

As far as I'm concerned, once #305 and #309 are merged, we're good to tag

**Comment by simonschoelly** [comment]
@gdalle we can close this, right?
