### ISSUE TITLE
[BUG] Intermittently failing tests for `label_propagation` on mac OS

### ISSUE THREAD

**Issue by etiennedeg** [JuliaGraphs/Graphs.jl#83]
Examples of failing tests [here](https://github.com/JuliaGraphs/Graphs.jl/runs/4619930056?check_suite_focus=true) and [here](https://github.com/JuliaGraphs/Graphs.jl/runs/4336947072?check_suite_focus=true)

**Comment by simonschoelly** [comment]
This is probably due to the probabilistic nature of that algorithm, and might not have anything to do with the operating system. Possible solutions are:
- Repeat the algorithm often enough and ensure that it succeeds enough times (i.e. fails with a very low probability)
- Add the possibility to pass a random number generator or a  seed to that function, then make it deterministic during testing.

As all probabilistic functions should have the ability to pass a random number generator, I would prefer the second approach.

**Comment by etiennedeg** [comment]
[The diffusion test](https://github.com/JuliaGraphs/Graphs.jl/runs/4753115798?check_suite_focus=true) have the same problem
