### ISSUE TITLE
1.5 silently dropped julia 1.3 support

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGraphs/Graphs.jl#86]
If I interpret the logs correctly, it looks like 1.3 isn't supported anymore:
https://github.com/JuliaPlots/Makie.jl/runs/4753606377?check_suite_focus=true#step:6:284
Was this on purpose?

**Comment by simonschoelly** [comment]
Definitely not, although it might make sense to do that at some point.. If you look at the [Project.toml](https://github.com/JuliaGraphs/Graphs.jl/blob/v1.5.0/Project.toml),we also do not specify any minor version for Julia. Apart from the version number, nothing in that file seems to have changed since v1.4.1, so I am not sure what is going on here.

**Comment by simonschoelly** [comment]
Apparently we do not check for specific Julia versions in our CI/CD scripts: https://github.com/JuliaGraphs/Graphs.jl/blob/master/.github/workflows/ci.yml. Not sure why, but could explain why we might have missed some bug on older Julia versions.

**Comment by simonschoelly** [comment]
Looks like a PR that was merged into the newest release uses some syntax that does not work on Julia v1.3: https://github.com/JuliaGraphs/Graphs.jl/blob/c2e41703cb403246379d82591594f6cd18d43946/src/operators.jl#L847. I will try to fix that asap.

**Comment by simonschoelly** [comment]
Fixed by #87

**Comment by SimonDanisch** [comment]
Thanks for the quick fix!
